routes/web.php
<?php
use Illuminate\Support\Facades\Input;
use App\Boutiquier_Vente;

/* v b
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/* Route::get('test', function(){
    return App\User::with('orders')->get();
}); */

//test

//products functions
//Route::view('/produitsss', 'front.index');

//Route::view('productss','front.products',
 //['data'=> App\Product::all(),'catByUser' => 'All Products']);
//Route::get('products/{cat}','TestController@proCat');
//Route::get('searchsss','TestController@search');
//Route::get('productsCat','ProductController@getCatalogue');
//Route::get('details/{id}', 'TestController@details');
// products functions end 
  
// test
Route::resource('evaluation', 'EvaluationController');
Route::get('/export_excel/excel', 'ProductController@excel')->name('export_excel.excel');
Route::get('export/{type}', 'ProductController@export')->name('export/xls');
Route::get('exporter_com/{type}', 'OderController@export_commerciaux')->name('exporter_com/xls'); 
Route::get('exporter_free/{type}', 'OderController@export_freelance')->name('exporter_free/xls');  
Route::get('exporter_bou/{type}', 'OderController@export_boutiquier')->name('exporter_bou/xls');  
Route::get('exporter_cli/{type}', 'OderController@export_client')->name('exporter_cli/xls');  

Route::get('generate-pdf','ProductController@generatePDF');

//orange money
Route::get('/myApi','PaiementController@orange_money');
Route::get('/api','OderController@retour_gestion');
//Route::post('/myApi','PaiementController@myApi');
//Route::post('/myApi','PaiementController@myApi');



Route::get('/testFourni', 'FournisseurController@test');
Route::get('/admin/banFournisseur', 'FournisseurController@banFournisseur');


Route::get('/changePassword','HomeController@showChangePasswordForm');
Route::post('/changePassword','HomeController@changePassword')->name('changePassword');
//Route::get('catalogues/category/{categorie_id}', 'TopController@tests');
Route::get('catalogues/category/{categorie_id}', 'CategoryController@test');
Route::get('/admin/banCategory', 'CategoryController@banCategory');
Route::get('tester', 'CategoryController@test');//->name('test_catalogues');
Route::get('catalogues/{category}', 'CategoryController@proCat');
Route::get('/productsCat','ProductController@productsCat');
Route::get('testez', 'OderController@test');


//made in senegal
Route::get('/made_senegal', 'TopController@made_senegal');
Route::GET('/details_produit/{id}','TopController@details_made')->name('details.produit');


//commercesup
Route::get('lister/c_commercesup', 'CommercialController@lister_commercesup');
Route::get('ajout/c_commercesup', 'CommercialController@ajout_commercesup');
Route::post('save/c_commercesup', 'CommercialController@save_commercesup')->name('commercial_commercesup.ajout');
Route::get('lister/b_commercesup', 'BoutiqueController@lister_commercesup');
Route::get('ajout/b_commercesup', 'BoutiqueController@ajout_commercesup');
Route::post('save/b_commercesup', 'BoutiqueController@save_commercesup')->name('boutique_commercesup.ajout');


//jalo ecommerce route verrsion
Route::get('jalo/', 'TopController@jalo');
Route::get('jalo/{details}', 'DetailsController@details')->name('jalo.details');
Route::get('jalo/{promo}', 'DetailsController@promo')->name('jalo.promo');
Route::get('jalo/{vente}', 'DetailsController@vente')->name('jalo.vente');
Route::view('jalo/produits', 'version3.layouts.index',[
    
    'produits' => App\Product::all()
  ]);
Route::get('actualite', 'TopController@actualite'); 

Route::get('vendeur','TypeController@vendeur');
Route::get('fournisseurss','TypeController@fournisseur');

Route::get("/catalogue/jalo","TopController@mySearchss");
Route::get('mentions', 'TopController@mentions'); 

//Route::get('/','TopController@jalo');
Route::post('/','TopController@store');
//Rejoindre
Route::get('ajout/fourni', 'TypeController@ajout_fournisseur');
Route::post('ajout/fournis', 'TypeController@save_fournisseur')->name('ajout.fournis');
Route::get('ajout/commerci', 'TypeController@ajout_commercial');
Route::post('ajout/commercis', 'TypeController@save_commercial')->name('ajout.commercis');
Route::get('ajout/bouti', 'TypeController@ajout_boutiquier');
Route::post('ajout/boutis', 'TypeController@save_boutiquier')->name('ajout.boutis');

//Sous Categories
Route::get('lister/SousCat', 'CategoryController@lister_SousCat');
Route::get('ajout/SousCategorie', 'CategoryController@ajout_SousCategorie');
Route::post('save/SousCate', 'CategoryController@save_SousCate')->name('ajout.SousCate');
Route::DELETE('soucat/{souscat}', 'CategoryController@supprimer')->name('souscat.destroy');

// Addresse_livraison
Route::get('addresse_livraison', 'AddressController@Addresse_livraison');
Route::get('addresse/livraison', 'AddressController@Addresse_livraisonss');
Route::get('cat_sous', 'CategoryController@cat_sou');


//A propos
Route::get('a-propos','TypeController@a_propos');

//visual image

Route::get('visuals', 'VisualController@visuals');
Route::resource('imagevisuals','ImageVisualController');



//partenaire

Route::get('partenaires', 'PartenaireController@Partenaires');
  
//categorie


//products functions
Route::view('testproducts','front.products',
 ['data'=> App\Product::all(),'catByUser' => 'All Product']);
Route::get('testproducts/{cat}','TestController@proCat');
Route::get('testsearchsss','TestController@search');
Route::get('testproductsCat','TestController@test_productsCat');
Route::get('testdetails/{id}', 'TestController@details');
// products functions end

//Produit top
Route::get('/top_promo', 'TopController@top_promo');
Route::get('/top_vente', 'TopController@top_vente');
Route::get('/produit_jour', 'TopController@produit_jour');


Route::get('checkout', 'CartController@Checkout');

//Route::get('/calculer', 'Boutique_VenteController@calculer');
//Route::post('/calc', 'Boutique_VenteController@calc');
Route::get('/searchs', 'Boutique_VenteController@searchs');
Route::any('/search', 'Boutique_VenteController@search');

Route::get("/my-search","Boutique_VenteController@mySearch");

Route::get("/my-searchs","Fourni_VenteController@mySearch");

Route::get("/catalogue/{category}","ProductController@mySearch");


/* Route::get ( '/search', function () {
    return view('boutiquier.search_boutiquier');
    } );
Route::any('/search', function () {
    $q = Input::get('q');
    $boutiquier = Boutiquier_Vente::where('nomProduit','LIKE','%'.$q.'%')->orWhere('boutique_id','LIKE','%'.$q.'%')->get();
if (count($boutiquier) > 0)
    return view('boutiquier.search_boutiquier')->withDetails($boutiquier)->withQuery($q);
else
    return view('boutiquier.search_boutiquier')->withMessage('No Details found. Try to search again !');
} ); */

Route::view('/layouts/showProduit', 'layouts/showProduit');

Route::get('/user/find', 'SearchController@searchCategories');

//Route::get('/category/find', 'SearchController@searchCategorie');

//Route::get('/categorie/find', 'SearchController@searchCategory');

//Route::get('searcher', 'SearchController@index')->name('searcher');





Route::get('/admin', 'AdminController@login');
//Route::get('/adm', 'AdminController@login');

Route::get('/deconnexion', 'AdminController@deconnexion');
Route::match(['get','post'], '/admin', 'AdminController@login');


Route::resource('product', 'ProductController');
Route::resource('category', 'CategoryController');
Route::resource('cart', 'CartController');
Route::resource('oder', 'OderController');
Route::resource('address', 'AddressController');
Route::resource('boutique', 'BoutiqueController');
Route::resource('quartier', 'QuartierController');
Route::resource('fournisseur', 'FournisseurController');
Route::resource('commercial', 'CommercialController');
Route::resource('fournisseur_vente', 'Fourni_VenteController');
Route::resource('boutique_vente', 'Boutique_VenteController');
Route::resource('posts', 'PostController');
Route::resource('freelance', 'FreelanceController');
Route::resource('livreur', 'LivreurController');



Route::get('quartier', 'QuartierController@index');

//Route::get('getImages', 'ProductController@getImages');



Route::get('product', 'ProductController@lister');

Route::get('boutique', 'BoutiqueController@index');

Route::get('paymentCart', 'CartController@payment');


Route::get('orders/{type?}', 'OderController@Orders');


Route::get('/cart/add-item/{id}', 'CartController@addItem')->name('cart.addItem');
Route::get('cart/removes/{id}', 'CartController@removeItem');
Route::get('cart/modified/','CartController@updateItem');
Route::get('checkCoupon','CheckoutController@checkCoupon');

//Route::get('checkout', 'CheckoutController@index'); 
//Route::post('placeOrder','CheckoutController@placeOrder');
Route::get('/thankyou', 'OderController@thankyou');
Route::DELETE('/annuler/{annuler}','OderController@supprimer')->name('annuler.destroyed');

Route::get('/thankyou/{id}', 'OderController@thankyouOM')->name('orange.money');  



/* Route::get('thankyou',function(){
  return view('thankyou');
});  */ 

Route::get('orderDetails/{id}',function($id){
    return view('myaccount.order');
  });
  
  Route::get('trackOrder/{id}',function($id){
    $orderData = App\Order::where('id',$id)->get();
    return view('myaccount.track',['data' => $orderData]);
  });

//Route::get('/cart/add-item/{id}', 'Fourni_VenteController@addItem')->name('cart.addItem');



Route::get('/', 'TopController@jalo');
Route::get('/catalogues', 'ProductController@getCatalogue');
Route::get('/showProduit', 'ProductController@showProduit');
Route::get('/TESTER' , 'ProductController@TESTER');


//Route::get('/connexion', 'ClientController@formulaire');

resources/views/fallou.blade.php
<!doctype html>
<html class="no-js" lang="fr">
<head>
<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Jalo</title>
<link rel="stylesheet" href="../css/app.css">
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>


<body>

<header class="header">
<div class="header-top">
<div class="row">
<div class="small-12 medium-4 large-2">
<img src="../images/logo-yellow.jpeg" class="logo" alt="">
</div>
<div class="small-12 medium-8 large-6">
<div class="search">
<form action="">
<input type="search" class="search-input" placeholder="Rechercher un mot clé">
<button class="button button-search"><img src="../images/search-icon.png" alt="Rechercher icon"></button>
</form>
</div>
</div>
<div class="small-12 medium-12 large-3 large-offset-1">
<div class="user-session">
<ul class="dropdown menu" data-dropdown-menu>
<li><a href="" class="notification-is-active"><i class="tiny material-icons">notifications</i><span></span></a></li>
<li>
<a href="#" class="user-name"><i class="tiny material-icons">person</i>Client</a>
<ul class="menu">
<li><a href="profile.html"><i class="tiny material-icons">person</i> Profil</a></li>
<li><a href="#"><i class="tiny material-icons">settings</i> Paramettre</a></li>
<li><a href="/sign-in.html"><i class="tiny material-icons">exit_to_app</i> Se connecter</a></li>
</ul>
</li>
</ul>
</div>
</div>
</div>
</div>
<div class="row">
<div class="title-bar" data-responsive-toggle="example-animated-menu" data-hide-for="medium">
<button class="menu-icon" type="button" data-toggle></button>
<div class="title-bar-title">Menu</div>
</div>

<div class="top-bar" id="example-animated-menu" data-animate="hinge-in-from-top spin-out">
<div class="top-bar-left">
<ul class="menu">
<li><a href="catalogue.html" class="is-active waves-effect waves-yellow"><i class="tiny material-icons">view_module</i> <span>Catalogue</span></a></li>
<li><a href="ma-boutique.html" class="waves-effect waves-yellow"><i class="tiny material-icons">shop</i> <span>Ma boutique</span></a></li>
<li><a href="commandes.html" class="waves-effect waves-yellow"><i class="tiny material-icons">shopping_cart</i> <span>Commandes</span></a></li>
<li><a href="boutiques.html" class="waves-effect waves-yellow"><i class="tiny material-icons">shop</i> <span>Boutiques</span></a></li>
<li><a href="promotions.html" class="waves-effect waves-yellow"><i class="tiny material-icons">shopping_basket</i> <span>Promo</span></a></li>
<li><a href="fournisseurs.html" class="waves-effect waves-yellow"><i class="tiny material-icons">local_shipping</i> <span>Fournisseurs</span></a></li>
</ul>
</div>
<div class="top-bar-right">
<ul class="menu">
<li><a href="#bucket-container" class="shopping-cart-notif modal-trigger"><i class="tiny material-icons">shopping_cart</i><span>3</span></a></li>
</ul>
</div>
</div>
</div>
</header>

<main class="main">
<div class="row">
<header class="header-main-content">
<div class="top-bar">
<div class="top-bar-left">
<ul class="menu">
<li> <a href="" class="button">Toutes les catégories</a> </li>
<li> <a href="" class="hollow button secondary">Matériels électronique</a> </li>
<li> <a href="" class="hollow button secondary">Vétements</a> </li>
<li> <a href="" class="hollow button secondary">Consommation courante</a> </li>
</ul>
</div>
<div class="top-bar-right pos-rltv">
<div class="fixed-action-btn horizontal">
<a class="waves-effect waves-yellow btn-floating btn-large black">
<i class="material-icons">add_shopping_cart</i>
</a>
<!-- Modal Trigger -->
<ul>
<li>
<a class="waves-effect waves-black btn-floating green darken-1 modal-trigger" href="#create-shop" data-position="bottom" data-delay="50" data-tooltip="Faire une commande">
<i class="material-icons">add_shopping_cart</i>
</a>
</li>
</ul>
</div>
</div>
</div>
</header>
</div>

        <div class="row">
        @foreach($catalogues as $catalogue)

                <div class="small-12 medium-6 large-3 p-10">
                    <div class="card card-center">
                        <img src="https://source.unsplash.com/collection/190727" alt="">
                            <div class="card-section">
                            <a href="/produit/{{$catalogue->id}}"><h4 class="card-title">{{ ucfirst($catalogue->produit) }}</h4></a>
                            <small class="card-sub-title">{{ ucfirst($catalogue->prenom) }} {{$catalogue->nom}}</small>

                                    <div class="card-wrap-price">
                                        @if($catalogue->promo_prix != 0)
                                            <strong class="card-price-old">{{$catalogue->prix}}<span>F CFA</span></strong>
                                            <strong class="card-price">{{$catalogue->promo_prix}}<span>F CFA</span></strong>
                                        @else
                                            <strong class="card-price">{{$catalogue->prix}}<span>F CFA</span></strong>
                                        @endif
                                    </div>
                                    
          <button class="add-bucket-btn waves-effect waves-black add_to_cart" id="add_btn">tine</button>

                                    <div class="alert alert-success" id="successMsg"></div>
                            </div>
                    </div>
                </div>

@endforeach
        </div>


<div class="row">
<div class="small-12 medium-12 large-12">
<ul class="pagination text-center" role="navigation" aria-label="Pagination">
<li class="pagination-previous disabled">Précédent</li>
<li class="current"><span class="show-for-sr">Page courante</span> 1</li>
<li><a href="#" aria-label="Page 2">2</a></li>
<li><a href="#" aria-label="Page 3">3</a></li>
<li><a href="#" aria-label="Page 4">4</a></li>
<li class="ellipsis"></li>
<li><a href="#" aria-label="Page 12">12</a></li>
<li><a href="#" aria-label="Page 13">13</a></li>
<li class="pagination-next"><a href="#" aria-label="Next page">Suivant</a></li>
</ul>
</div>
</div>






                
                   
        
                
           

               

         
</body>
</html>

resources/views/flash-message.blade.php
@if ($message = Session::get('success'))

<div class="alert alert-success alert-block">

	<button type="button" class="close" data-dismiss="alert">×</button>	

        <strong>{{ $message }}</strong>

</div>

@endif


@if ($message = Session::get('error'))

<div class="alert alert-danger alert-block">

	<button type="button" class="close" data-dismiss="alert">×</button>	

        <strong>{{ $message }}</strong>

</div>

@endif


@if ($message = Session::get('warning'))

<div class="alert alert-warning alert-block">

	<button type="button" class="close" data-dismiss="alert">×</button>	

	<strong>{{ $message }}</strong>

</div>

@endif


@if ($message = Session::get('info'))

<div class="alert alert-info alert-block">

	<button type="button" class="close" data-dismiss="alert">×</button>	

	<strong>{{ $message }}</strong>

</div>

@endif


@if ($errors->any())

<div class="alert alert-danger">

	<button type="button" class="close" data-dismiss="alert">×</button>	

	Please check the form below for errors

</div>

@endif

resources/views/home.blade.php
@extends('layout.deco1')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card" style="margin-top:50px;">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif


                           <strong>MERCI <p>{{ Auth::user()->name }} ! Votre compte a bien été créé</p></strong>
                           <b><a href="/cart" class="button" style="background-color:black; color:yellow; font-size:18px;">Poursuivre votre commande</a></b>
   </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/master.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <h2>Dropdowns</h2>
  <p>The .dropdown class is used to indicate a dropdown menu.</p>
  
  <div class="dropdown">
 
    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">drop
    <span class="caret"></span></button>

		
		
    <ul class="dropdown-menu">

    @foreach(App\Category::with('childs')
    ->where('product_id',0)->get() as $item)

            @if($item->childs->count()>0)
					
								<li><a href="{{url('catalogues')}}/{{$item->name}}"><h4>{{$item->name}}</h4></a></li>

								    @foreach($item->childs as $subMenu)
										
												<li><a href="{{url('catalogues')}}/{{$subMenu->name}}">{{$subMenu->name}}</a></li>
									
										@endforeach

						
				@else

				<li><a href="{{url('catalogues')}}/{{$item->name}}"><h4>{{$item->name}}</h4></a></li>
				@endif
				
		@endforeach

    </ul>
	


</div>
<div class="row">
<form action="">
        <div class="row row-filter">
          
          <div class="small-12 medium-6 large-4 p-0-15">
            <label for="">
              <strong>Catégorie</strong>
              <select id="catID">
							   <option value="">Select a Category</option>
                
                 <option class="option" value=""></option>
               </select>
            </label>
          </div>
          
          <div class="small-12 medium-6 large-2 p-0-15">
            <label for="">
              <strong>Prix</strong>
              <select id="priceID">
                <option value="0" selected>Croissant / Décroissant</option>
                <option value="0-100000">Décroissant</option>
						    <option value="100000-200000">Croissant</option>
						    
              </select>
            </label>
          </div>

          <div class="small-12 medium-12 large-2 p-0-15">
          <button id="findBtn" onClick="find()" class="filter-button">Filtrer</button>
          </div>

        </div>

      </div>
</form>
</div>

</body>
</html>

resources/views/newsletter.blade.php
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Laravel Newsletter Tutorial With Example</title>
    <link rel="stylesheet" href="{{asset('css/app.css')}}">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">    
  </head>
  <body>
    <div class="container">
    @if (\Session::has('success'))
      <div class="alert alert-success">
        <p>{{ \Session::get('success') }}</p>
      </div><br />
     @endif
     @if (\Session::has('failure'))
      <div class="alert alert-danger">
        <p>{{ \Session::get('failure') }}</p>
      </div><br />
     @endif
      <h2>Laravel Newsletter Tutorial With Example</h2><br/>
      <form method="post" action="{{url('newsletter')}}">
        @csrf
        </div>
        <div class="row">
          <div class="col-md-4"></div>
            <div class="form-group col-md-2">
              <label for="Email">Email:</label>
              <input type="text" class="form-control" name="email">
            </div>
          </div>
        <div class="row">
          <div class="col-md-4"></div>
          <div class="form-group col-md-4">
            <button type="submit" class="btn btn-success">Submit</button>
          </div>
        </div>
      </form>
    </div>
  </body>
</html>

resources/views/test.blade.php
<!doctype html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>JALÔSHOPS-Tout près de chez vous</title>
    <link rel="stylesheet" href="{{asset('css/jalo/app.css')}}">
    <link rel="stylesheet" href="{{asset('css/jalo/brandon/style.css')}}">

  </head>
  <body>

    <!--header-->
@include('version3.header.header1')

<!-- end header--> 

    <main class="main">
    @include('version3.layouts.ourJs')

      <!-- Filter -->
      <form action="">
        <div class="row row-filter">
          <div class="small-12 medium-6 large-4 p-0-15">
            <label for="">
              <strong>Nom produit</strong>
              <input type="text" placeholder="Nom du produit" name="search" value="{{ old('search') }}">
            </label>
          </div>
          <div class="small-12 medium-6 large-4 p-0-15">
            <label for="">
              <strong>Catégorie</strong>
              <select id="catID">
							   <option value="">Selectionner Categorie</option>
                 @foreach(App\Category::all() as $cList)
                 <option class="option" value="{{$cList->id}}">{{$cList->name}}</option>
                 @endforeach
               </select>
            </label>
          </div>
          
          <div class="small-12 medium-6 large-2 p-0-15">
            <label for="">
              <strong>Prix</strong>
              <select id="priceID">
                <option value="0" selected>Croissant / Décroissant</option>
                <option value="0-100000">Décroissant</option>
						    <option value="100000-200000">Croissant</option>
						    
              </select>
            </label>
          </div>

          <div class="small-12 medium-12 large-2 p-0-15">
          <button id="findBtn" onClick="find()" class="filter-button">Filtrer</button>
          </div>

        </div>

      </form>
      <p>&nbsp;</p>
      <!-- End filter -->
      
      <div class="row">

@if(count($data)=="0")
        <div class="col-md-12" align="center">

          <h1 style="font-size:20px;">Aucun data Trouvés</h1>

              
        </div>
        @else 
        <div class="products">
        @foreach($data as $produit)

                <div class="products-item">
                <a href="{{route('product.show', $produit->id)}}"><img src="{{url('images', $produit->image)}}" onmouseover="this.src='{{url('images', $produit->category->image)}}'" onmouseout="this.src='{{url('images', $produit->image)}}'" alt="" class="products-item-img"></a>
                            <div class="products-item-info">
                            <a href="{{route('product.show', $produit->id)}}"><h5 class="products-item-info-title">{{ $produit->name}}</h5></a>
<!--                             <p>Description: {{ $produit->description}}</p>
 -->                                        <div class="products-item-info-footer">
                                            <span class="price">{{ $produit->price}} F CFA</span>
                                            <a href="{{route('product.show', $produit->id)}}">Voir Détails</a>
                                        </div>
                            </div>
                            <div class="add-bucket">
                            <form action="">
                            <a href="{{route('cart.addItem', $produit->id)}}" class="add-bucket-icon"><img src="{{asset('images/jalo/icons/bucket.svg')}}" alt=""></a>
                            </form>
                            </div>
                </div>
                @endforeach

        </div>
@endif
        <div class="see-more">
        
        </div>

      </div>
      
    </main>

   <!-- foooter -->
   @include('version3.footer.footer')

<!-- end footer-->

    <script src="{{asset('js/jalo/jquery.min.js')}}"></script>
    <script src="{{asset('js/jalo/what-input.min.js')}}"></script>
    <script src="{{asset('js/jalo/foundation.min.js')}}"></script>
    <script src="{{asset('js/jalo/slick.min.js')}}"></script>
    <script src="{{asset('js/jalo/app.js')}}"></script>
   @include('front.ourJs')

  </body>
</html>

resources/views/thankyou.blade.php
@extends('layout.deco1')

@section('content')
<div class="greyBg">
    <div class="container">
		<div class="wrapper">
      <div class="row">
				<div class="col-sm-12">
				 <div class="breadcrumbs" style="margin-top:50px;">
			        <ul style="display:flex; margin-left:420px;">
			          <li ><a href="{{url('/')}}" style="color:black;"><strong><b>Home</b></strong></a></li>
                 <li><span class="dot">/</span>
			          <a href="{{url('/myaccount')}}" style="color:black;"><strong><b>{{Auth::user()->name}}</b></strong></a></li>
                <li><span class="dot">/</span>
                  <a href="" style="color:black;"><strong><b>On vous remercie</b></strong></a>
			        </ul>
                        </div>
                    </div>
         </div> 

         <div class="callout secondary">
            <h5><strong>MERCI!  <p><b>{{ Auth::user()->name }}</b></p></strong></h5>
            <p><b>Votre livraison sera faite d'ici 48H.</b></p>
            <a href="{{url('/myaccount')}}" class="button"><strong>Votre Commande se trouve ici</strong></a>

  
          </div>

               
                        
        </div>
    </div>
  </div>
</div>
<style>
ul li {
}
.button{
  background-color:yellow;
  color:black;
}

.button:hover{
  background-color:black;
  color:yellow;
}

</style>
@endsection