routes/web.php
<?php
use Illuminate\Support\Facades\Input;
use App\Boutiquier_Vente;

/* v b
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/* Route::get('test', function(){
    return App\User::with('orders')->get();
}); */

//test

//products functions
//Route::view('/produitsss', 'front.index');

//Route::view('productss','front.products',
 //['data'=> App\Product::all(),'catByUser' => 'All Products']);
//Route::get('products/{cat}','TestController@proCat');
//Route::get('searchsss','TestController@search');
//Route::get('productsCat','ProductController@getCatalogue');
//Route::get('details/{id}', 'TestController@details');
// products functions end 
  
// test
Route::resource('evaluation', 'EvaluationController');
Route::get('/export_excel/excel', 'ProductController@excel')->name('export_excel.excel');
Route::get('export/{type}', 'ProductController@export')->name('export/xls');
Route::get('exporter_com/{type}', 'OderController@export_commerciaux')->name('exporter_com/xls'); 
Route::get('exporter_free/{type}', 'OderController@export_freelance')->name('exporter_free/xls');  
Route::get('exporter_bou/{type}', 'OderController@export_boutiquier')->name('exporter_bou/xls');  
Route::get('exporter_cli/{type}', 'OderController@export_client')->name('exporter_cli/xls');  

Route::get('generate-pdf','ProductController@generatePDF');

//orange money
Route::get('/myApi','PaiementController@orange_money');
Route::get('/api','OderController@retour_gestion');
//Route::post('/myApi','PaiementController@myApi');
//Route::post('/myApi','PaiementController@myApi');



Route::get('/testFourni', 'FournisseurController@test');
Route::get('/admin/banFournisseur', 'FournisseurController@banFournisseur');


Route::get('/changePassword','HomeController@showChangePasswordForm');
Route::post('/changePassword','HomeController@changePassword')->name('changePassword');
//Route::get('catalogues/category/{categorie_id}', 'TopController@tests');
Route::get('catalogues/category/{categorie_id}', 'CategoryController@test');
Route::get('/admin/banCategory', 'CategoryController@banCategory');
Route::get('tester', 'CategoryController@test');//->name('test_catalogues');
Route::get('catalogues/{category}', 'CategoryController@proCat');
Route::get('/productsCat','ProductController@productsCat');
Route::get('testez', 'OderController@test');


//made in senegal
Route::get('/made_senegal', 'TopController@made_senegal');
Route::GET('/details_produit/{id}','TopController@details_made')->name('details.produit');


//commercesup
Route::get('lister/c_commercesup', 'CommercialController@lister_commercesup');
Route::get('ajout/c_commercesup', 'CommercialController@ajout_commercesup');
Route::post('save/c_commercesup', 'CommercialController@save_commercesup')->name('commercial_commercesup.ajout');
Route::get('lister/b_commercesup', 'BoutiqueController@lister_commercesup');
Route::get('ajout/b_commercesup', 'BoutiqueController@ajout_commercesup');
Route::post('save/b_commercesup', 'BoutiqueController@save_commercesup')->name('boutique_commercesup.ajout');


//jalo ecommerce route verrsion
Route::get('jalo/', 'TopController@jalo');
Route::get('jalo/{details}', 'DetailsController@details')->name('jalo.details');
Route::get('jalo/{promo}', 'DetailsController@promo')->name('jalo.promo');
Route::get('jalo/{vente}', 'DetailsController@vente')->name('jalo.vente');
Route::view('jalo/produits', 'version3.layouts.index',[
    
    'produits' => App\Product::all()
  ]);
Route::get('actualite', 'TopController@actualite'); 

Route::get('vendeur','TypeController@vendeur');
Route::get('fournisseurss','TypeController@fournisseur');

Route::get("/catalogue/jalo","TopController@mySearchss");
Route::get('mentions', 'TopController@mentions'); 

//Route::get('/','TopController@jalo');
Route::post('/','TopController@store');
//Rejoindre
Route::get('ajout/fourni', 'TypeController@ajout_fournisseur');
Route::post('ajout/fournis', 'TypeController@save_fournisseur')->name('ajout.fournis');
Route::get('ajout/commerci', 'TypeController@ajout_commercial');
Route::post('ajout/commercis', 'TypeController@save_commercial')->name('ajout.commercis');
Route::get('ajout/bouti', 'TypeController@ajout_boutiquier');
Route::post('ajout/boutis', 'TypeController@save_boutiquier')->name('ajout.boutis');

//Sous Categories
Route::get('lister/SousCat', 'CategoryController@lister_SousCat');
Route::get('ajout/SousCategorie', 'CategoryController@ajout_SousCategorie');
Route::post('save/SousCate', 'CategoryController@save_SousCate')->name('ajout.SousCate');
Route::DELETE('soucat/{souscat}', 'CategoryController@supprimer')->name('souscat.destroy');

// Addresse_livraison
Route::get('addresse_livraison', 'AddressController@Addresse_livraison');
Route::get('addresse/livraison', 'AddressController@Addresse_livraisonss');
Route::get('cat_sous', 'CategoryController@cat_sou');


//A propos
Route::get('a-propos','TypeController@a_propos');

//visual image

Route::get('visuals', 'VisualController@visuals');
Route::resource('imagevisuals','ImageVisualController');



//partenaire

Route::get('partenaires', 'PartenaireController@Partenaires');
  
//categorie


//products functions
Route::view('testproducts','front.products',
 ['data'=> App\Product::all(),'catByUser' => 'All Product']);
Route::get('testproducts/{cat}','TestController@proCat');
Route::get('testsearchsss','TestController@search');
Route::get('testproductsCat','TestController@test_productsCat');
Route::get('testdetails/{id}', 'TestController@details');
// products functions end

//Produit top
Route::get('/top_promo', 'TopController@top_promo');
Route::get('/top_vente', 'TopController@top_vente');
Route::get('/produit_jour', 'TopController@produit_jour');


Route::get('checkout', 'CartController@Checkout');

//Route::get('/calculer', 'Boutique_VenteController@calculer');
//Route::post('/calc', 'Boutique_VenteController@calc');
Route::get('/searchs', 'Boutique_VenteController@searchs');
Route::any('/search', 'Boutique_VenteController@search');

Route::get("/my-search","Boutique_VenteController@mySearch");

Route::get("/my-searchs","Fourni_VenteController@mySearch");

Route::get("/catalogue/{category}","ProductController@mySearch");


/* Route::get ( '/search', function () {
    return view('boutiquier.search_boutiquier');
    } );
Route::any('/search', function () {
    $q = Input::get('q');
    $boutiquier = Boutiquier_Vente::where('nomProduit','LIKE','%'.$q.'%')->orWhere('boutique_id','LIKE','%'.$q.'%')->get();
if (count($boutiquier) > 0)
    return view('boutiquier.search_boutiquier')->withDetails($boutiquier)->withQuery($q);
else
    return view('boutiquier.search_boutiquier')->withMessage('No Details found. Try to search again !');
} ); */

Route::view('/layouts/showProduit', 'layouts/showProduit');

Route::get('/user/find', 'SearchController@searchCategories');

//Route::get('/category/find', 'SearchController@searchCategorie');

//Route::get('/categorie/find', 'SearchController@searchCategory');

//Route::get('searcher', 'SearchController@index')->name('searcher');





Route::get('/admin', 'AdminController@login');
//Route::get('/adm', 'AdminController@login');

Route::get('/deconnexion', 'AdminController@deconnexion');
Route::match(['get','post'], '/admin', 'AdminController@login');


Route::resource('product', 'ProductController');
Route::resource('category', 'CategoryController');
Route::resource('cart', 'CartController');
Route::resource('oder', 'OderController');
Route::resource('address', 'AddressController');
Route::resource('boutique', 'BoutiqueController');
Route::resource('quartier', 'QuartierController');
Route::resource('fournisseur', 'FournisseurController');
Route::resource('commercial', 'CommercialController');
Route::resource('fournisseur_vente', 'Fourni_VenteController');
Route::resource('boutique_vente', 'Boutique_VenteController');
Route::resource('posts', 'PostController');
Route::resource('freelance', 'FreelanceController');
Route::resource('livreur', 'LivreurController');



Route::get('quartier', 'QuartierController@index');

//Route::get('getImages', 'ProductController@getImages');



Route::get('product', 'ProductController@lister');

Route::get('boutique', 'BoutiqueController@index');

Route::get('paymentCart', 'CartController@payment');


Route::get('orders/{type?}', 'OderController@Orders');


Route::get('/cart/add-item/{id}', 'CartController@addItem')->name('cart.addItem');
Route::get('cart/removes/{id}', 'CartController@removeItem');
Route::get('cart/modified/','CartController@updateItem');
Route::get('checkCoupon','CheckoutController@checkCoupon');

//Route::get('checkout', 'CheckoutController@index'); 
//Route::post('placeOrder','CheckoutController@placeOrder');
Route::get('/thankyou', 'OderController@thankyou');
Route::DELETE('/annuler/{annuler}','OderController@supprimer')->name('annuler.destroyed');

Route::get('/thankyou/{id}', 'OderController@thankyouOM')->name('orange.money');  



/* Route::get('thankyou',function(){
  return view('thankyou');
});  */ 

Route::get('orderDetails/{id}',function($id){
    return view('myaccount.order');
  });
  
  Route::get('trackOrder/{id}',function($id){
    $orderData = App\Order::where('id',$id)->get();
    return view('myaccount.track',['data' => $orderData]);
  });

//Route::get('/cart/add-item/{id}', 'Fourni_VenteController@addItem')->name('cart.addItem');



Route::get('/', 'TopController@jalo');
Route::get('/catalogues', 'ProductController@getCatalogue');
Route::get('/showProduit', 'ProductController@showProduit');
Route::get('/TESTER' , 'ProductController@TESTER');


//Route::get('/connexion', 'ClientController@formulaire');

resources/views/boutiquier/ajout_commercesup.blade.php
@extends('layout.adminlayout.design1')

@section('content')
<div id="right-panel" class="right-panel">

@include('layout.adminlayout.header')

@include('layout.adminlayout.section')


<div class="content mt-3">
   
            <div class="animated fadeIn">


                <div class="row" style="margin-left:250px;">
                  <div class="col-lg-8">
                    <div class="card">
                        <div class="card-header">
                            <center><strong class="card-title">Boutiquier</strong></center>
                        </div>
                        <div class="card-body">
                          <!-- Credit Card -->
                          <div id="pay-invoice">
                              <div class="card-body">
                                  
                                  <hr>
                                  {!! Form::open(['route'=>'boutique_commercesup.ajout', 'method' => 'post', 'files' => true, 'class'=>'form-horizontal']) !!}
                                      <div class="form-group text-center">
                                          <ul class="list-inline">
                                             
                                          </ul>
                                      </div>
                                      <div class="form-group">
                                          <label for="nom" class="control-label mb-1">Nom du Boutiquier</label>
                                          <input id="nom" name="nom" type="text" class="form-control" aria-required="true" aria-invalid="false" required>
                                      </div>

                                       <div class="form-group">
                                          <label for="adresse" class="control-label mb-1">Adresse du Boutiquier</label>
                                          <input id="adresse" name="adresse" type="text" class="form-control" aria-required="true" aria-invalid="false" required>
                                      </div>

                                       <div class="form-group">
                                          <label for="phone" class="control-label mb-1">Téléphone du Boutiquier</label>
                                          <input id="phone" name="phone" type="text" class="form-control" aria-required="true" aria-invalid="false" required>
                                      </div>
                                    
                                      <div class="form-group">
                                      <label for="quartier_id" class="control-label mb-1">Quartier du Boutiquier</label>
                                          <div class="col-md-10">
                                          {!! Form::select('quartier_id',$quartiers, null, ['class'=>'form-controll', 'placeholder'=> 'select quartier du boutiquier']) !!}
                                          {!! $errors->has('quartier_id')?$errors->first('quartier_id'):'' !!}
                                          </div>
                                      </div>

                                      <div class="form-group">
                                      <label for="commercial_id" class="control-label mb-1">Commercial</label>
                                          <div class="col-md-10">
                                          {!! Form::select('commercial_id',$commercials, null, ['class'=>'form-controll', 'placeholder'=> 'selectionner commercial']) !!}
                                          {!! $errors->has('commercial_id')?$errors->first('commercial_id'):'' !!}
                                          </div>
                                        </div>

                                      <div>
                                          <button id="submit" name="submit" style="margin-top:20px; background-color:yellow; color:black;" type="submit" class="btn btn-lg btn-block">
                                          Ajouter
                                          </button>
                                      </div>
                                      {!! Form::close() !!} 
                              </div>
                          </div>

                        </div>
                    </div> <!-- .card -->

                  </div><!--/.col-->
                  </div>

                  </div>
                  </div>
                  </div>

                  @endsection

resources/views/boutiquier/boutiquier.blade.php
<!doctype html>
<html class="no-js" lang="fr">
<head>
<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="csrf-token" content="{{ csrf_token() }}">
<title>Jalo</title>
<link rel="stylesheet" href="../css/app.css">
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<style>

#presentation {
  width: 480px;
  height: 120px;
  padding: 20px;
  margin: auto;
  background: #FFF;
  margin-top: 10px;
  box-shadow: 0 3px 6px rgba(0, 0, 0, 0.16), 0 3px 6px rgba(0, 0, 0, 0.23);
  transition: all 0.3s;
  border-radius: 3px;
}

#presentation:hover {
  box-shadow: 0 14px 28px rgba(0, 0, 0, 0.25), 0 10px 10px rgba(0, 0, 0, 0.22);
  transition: all 0.3s;
  transform: translateZ(10px);
}

#floating-button {
  width: 50px;
  height: 50px;
  border-radius: 50%;
  background:black;
  position: fixed;
  bottom: 30px;
  right: 30px;
  cursor: pointer;
  box-shadow: 0px 2px 5px yellow;
}

.plus {
  color: white;
  position: absolute;
  top: 0;
  display: block;
  bottom: 0;
  left: 0;
  right: 0;
  text-align: center;
  padding: 0;
  margin: 0;
  line-height: 55px;
  font-size: 38px;
  font-family: 'Roboto';
  font-weight: 300;
  animation: plus-out 0.3s;
  transition: all 0.3s;
}

#container-floating {
  position: fixed;
  width: 70px;
  height: 70px;
  bottom: 30px;
  right: 30px;
  z-index: 50px;
}

#container-floating:hover {
  height: 400px;
  width: 90px;
  padding: 30px;
}

#container-floating:hover .plus {
  animation: plus-in 0.15s linear;
  animation-fill-mode: forwards;
}

.edit {
  position: absolute;
  top: 0;
  display: block;
  bottom: 0;
  left: 0;
  display: block;
  right: 0;
  padding: 0;
  opacity: 0;
  margin: auto;
  line-height: 65px;
  transform: rotateZ(-70deg);
  transition: all 0.3s;
  animation: edit-out 0.3s;
}

#container-floating:hover .edit {
  animation: edit-in 0.2s;
  animation-delay: 0.1s;
  animation-fill-mode: forwards;
}

@keyframes edit-in {
  from {
    opacity: 0;
    transform: rotateZ(-70deg);
  }
  to {
    opacity: 1;
    transform: rotateZ(0deg);
  }
}

@keyframes edit-out {
  from {
    opacity: 1;
    transform: rotateZ(0deg);
  }
  to {
    opacity: 0;
    transform: rotateZ(-70deg);
  }
}

@keyframes plus-in {
  from {
    opacity: 1;
    transform: rotateZ(0deg);
  }
  to {
    opacity: 0;
    transform: rotateZ(180deg);
  }
}

@keyframes plus-out {
  from {
    opacity: 0;
    transform: rotateZ(180deg);
  }
  to {
    opacity: 1;
    transform: rotateZ(0deg);
  }
}

.nds {
  width: 55px;
  height: 55px;
  border-radius: 50%;
  position: fixed;
  z-index: 300;
  transform: scale(0);
  cursor: pointer;
}



.nd5 {
  background-image: url('https://lh3.googleusercontent.com/-X-aQXHatDQY/Uy86XLOyEdI/AAAAAAAAAF0/TBEZvkCnLVE/w140-h140-p/fb3a11ae-1fb4-4c31-b2b9-bf0CFA835c27');
  background-size: 100%;
  right: 40px;
  bottom: 300px;
  animation-delay: 0.08s;
  animation: bounce-out-nds 0.1s linear;
  animation-fill-mode: forwards;
}

@keyframes bounce-nds {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
    transform: scale(1);
  }
}

@keyframes bounce-out-nds {
  from {
    opacity: 1;
    transform: scale(1);
  }
  to {
    opacity: 0;
    transform: scale(0);
  }
}

#container-floating:checked {  
  margin-top:0;
  opacity:1;
}

#container-floating:hover .nds {
  animation: bounce-nds 0.1s linear;
  animation-fill-mode: forwards;
}

#container-floating:hover .nd3 {
  animation-delay: 0.08s;
}

#container-floating:hover .nd4 {
  animation-delay: 0.15s;
}

#container-floating:hover .nd5 {
  animation-delay: 0.2s;
}

.letter {
  font-size: 23px;
  font-family: 'Roboto';
  color: white;
  position: absolute;
  left: 0;
  right: 0;
  margin: 0;
  top: 0;
  bottom: 0;
  text-align: center;
  line-height: 40px;
}

.reminder {
  position: absolute;
  left: 0;
  right: 0;
  margin: auto;
  top: 0;
  bottom: 0;
  line-height: 40px;
}

.profile {
  border-radius: 50%;
  width: 40px;
  position: absolute;
  top: 0;
  bottom: 0;
  margin: auto;
  right: 20px;
}


}
</style>

<body>

<header class="header">

            <div class="header-top">
                <div class="row">
                    <div class="small-12 medium-4 large-2">
                    <a href="/"><img src="../images/logo-yellow.jpeg" class="logo" alt=""></a>
                    </div>
                        
                </div>
            </div>

        <div class="row">

            <div class="top-bar" id="example-animated-menu" data-animate="hinge-in-from-top spin-out">

                <div class="top-bar-right">
                    <ul class="menu">
                    <li><a href="{{route('cart.index')}}" class="shopping-cart-notif modal-trigger"><i class="tiny material-icons">shopping_cart</i><span>{{Cart::count()}}</span></a></li>
                    </ul>
                </div>
            </div>
        </div>

</header>

<main class="main">


        <p>&nbsp;</p>
        <div class="row">    
            @foreach($boutiquiers as $boutiquier)
            <div class="small-12 medium-6 large-4 p-10">
                <div class="card card-profil">
                    <div class="card-section">
                        <div class="seller">
                            <div class="seller-details">
                                <h4>{{$boutiquier->nom}}</h4>
                                <ul>
                                    <li><p><i class="material-icons"></i><span>Adresse : {{ str_limit(ucfirst($boutiquier->adresse), 40)}}</span></p></li>
                                    <li><p><i class="material-icons"></i><span>Téléphone : {{$boutiquier->phone}}</span></p></li>
                                    <li></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <p>&nbsp;</p>
            </div>

            @endforeach
            {{ $boutiquiers->links() }}
        </div>
        
        <p>&nbsp;</p>

</main>
        <script src="{{asset('js/js/jquery.min.js')}}"></script>
    <script src="{{asset('js/js/app.js')}}"></script>
    <script src="{{asset('js/js/jquery3.js')}}"></script>
	<script src="{{asset('js/js/bootstrap.min.js')}}"></script>
		

<script type="text/javascript">


</script>
         
</body>
</html>

resources/views/boutiquier/lister.blade.php
@extends('layout.adminlayout.design2')

@section('content')
<div id="right-panel" class="right-panel">

@include('layout.adminlayout.header')

@include('layout.adminlayout.section')


<div class="content mt-3">

            <div class="animated fadeIn">


                <div class="row" style="">
                  <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <center><strong class="card-title">Boutiquiers</strong></center>
                        </div>
                        <div class="card-body">
                          <!-- Credit Card -->
                          <div id="pay-invoice">
                              <div class="card-body">
                                  
                                  <hr>
                                  <table border="3" class="table table-bordered table-responsive" style="margin-top:50px;">

                        <thead>
                        <tr>
                        <th>ID</th>
                        <th>Nom du Boutiquier</th>
                        <th>Nom d'utilisateur</th>
                        <th>Adresse du Boutiquier</th>
                        <th>Téléphone du Boutiquier</th>
                        <th>Date de Création</th>
                        <th colspan="2"><span style="margin-left:40px;">Actions</span></th>
                        </tr>
                        </thead>

                        <tbody>


                        @foreach($boutiquiers as $boutique)
                        <tr>
                        <td>{{ $boutique->id }}</td>
                        <td>{{ $boutique->nom }}</td>
                        <td>{{ $boutique->user_id }}</td>
                        <td>{{ $boutique->adresse }}</td>
                        <td>{{ $boutique->phone}}</td>
                        <td>{{ $boutique->created_at }}</td>

                        <td>
                        <a href="{{route('boutique.edit', $boutique->id)}}" class="btn btn-warning"><i class="fa fa-pencil-square-o" style="font-size:24px"></i>

                         </a>                  </td>
                        <td>
                        {!! Form::open(['method'=>'delete', 'route'=>['boutique.destroy', $boutique->id]]) !!}
                        <button type="submit" class="btn btn-dark"><i style="font-size:24px" class="fa">&#xf014;</i>
                                                </button>
                        {!! Form::close() !!}
                        </td>

                        </tr>
                        @endforeach

                      </tbody>
                      </table>
                      {{ $boutiquiers->links() }}

                              </div>
                          </div>

                        </div>
                    </div> <!-- .card -->

                  </div><!--/.col-->
                  </div>

                  </div>
                  </div>
                  </div>

                  @endsection
         

resources/views/boutiquier/lister_commercesup.blade.php
@extends('layout.adminlayout.design1')

@section('content')
<div id="right-panel" class="right-panel">

@include('layout.adminlayout.header')

@include('layout.adminlayout.section')


<div class="content mt-3">

            <div class="animated fadeIn">


                <div class="row" style="">
                  <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <center><strong class="card-title">Boutiquiers</strong></center>
                        </div>
                        <div class="card-body">
                          <!-- Credit Card -->
                          <div id="pay-invoice">
                              <div class="card-body">
                                  
                                  <hr>
                                  <table border="3" class="table table-bordered table-responsive" style="margin-top:50px;">

                        <thead>
                        <tr>
                        <th>ID</th>
                        <th>Nom du Boutiquier</th>
                        <th>Adresse du Boutiquier</th>
                        <th>Téléphone du Boutiquier</th>
                        <th>Date de Création</th>
                        <th colspan="2"><span style="margin-left:40px;">Actions</span></th>
                        </tr>
                        </thead>

                        <tbody>


                        @foreach($boutiquiers as $boutique)
                        <tr>
                        <td>{{ $boutique->id }}</td>
                        <td>{{ $boutique->nom }}</td>
                        <td>{{ $boutique->adresse }}</td>
                        <td>{{ $boutique->phone}}</td>
                        <td>{{ $boutique->created_at }}</td>

                        <td>
                        <a href="{{route('boutique.edit', $boutique->id)}}" class="btn btn-warning"><i class="fa fa-pencil-square-o" style="font-size:24px"></i>

                         </a>                  </td>
                        <td>
                        {!! Form::open(['method'=>'delete', 'route'=>['boutique.destroy', $boutique->id]]) !!}
                        <button type="submit" class="btn btn-dark"><i style="font-size:24px" class="fa">&#xf014;</i>
                                                </button>
                        {!! Form::close() !!}
                        </td>

                        </tr>
                        @endforeach

                      </tbody>
                      </table>
                      {{ $boutiquiers->links() }}

                              </div>
                          </div>

                        </div>
                    </div> <!-- .card -->

                  </div><!--/.col-->
                  </div>

                  </div>
                  </div>
                  </div>

                  @endsection
         